spring:
  datasource:
    url: jdbc:postgresql://${USER_SERVICE_DB_HOST}:${USER_SERVICE_DB_PORT}/${USER_SERVICE_DB_NAME}
    username: ${USER_SERVICE_DB_USER}
    password: ${USER_SERVICE_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${USER_SERVICE_DDL_AUTO:validate}
