spring:
  application:
    name: activity-service

server:
  port: 8082

app:
  rabbitmq:
    exchanges:
      fitness: fitness.exchange
    queues:
      activity: activity.queue
    routing-keys:
      activity: activity.tracking