spring:
  data:
    mongodb:
      uri: ${ACTIVITY_SERVICE_MONGO_URI}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never