spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/{application},classpath:/config/shared

server:
  port: 8888