spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}