#!/bin/bash
set -euo pipefail

: "${USER_SERVICE_DB_NAME:?USER_SERVICE_DB_NAME must be set}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE DATABASE ${USER_SERVICE_DB_NAME}'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${USER_SERVICE_DB_NAME}')\gexec
EOSQL

# Create app user only when different from postgres admin (prod). Dev uses POSTGRES_USER for both.
if [[ -n "${USER_SERVICE_DB_USER:-}" && -n "${USER_SERVICE_DB_PASSWORD:-}" && "${USER_SERVICE_DB_USER}" != "${POSTGRES_USER}" ]]; then
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DO \$\$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${USER_SERVICE_DB_USER}') THEN
        CREATE ROLE ${USER_SERVICE_DB_USER} WITH LOGIN PASSWORD '${USER_SERVICE_DB_PASSWORD}';
      END IF;
    END
    \$\$;
    GRANT ALL PRIVILEGES ON DATABASE ${USER_SERVICE_DB_NAME} TO ${USER_SERVICE_DB_USER};
EOSQL

  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${USER_SERVICE_DB_NAME}" <<-EOSQL
    GRANT ALL ON SCHEMA public TO ${USER_SERVICE_DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${USER_SERVICE_DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${USER_SERVICE_DB_USER};
EOSQL
fi
