services:

  mongodb:
    image: mongo:8

    container_name: mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  activity-service:
    build: .

    container_name: activity-service

    ports:
      - "8081:8081"

    environment:
      SPRING_PROFILES_ACTIVE: dev

    depends_on:
      - mongodb

volumes:
  mongo_data: